# fly.toml app configuration file generated for taylor-blog-backend on 2023-09-11T19:27:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "taylor-blog-backend"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
